### ISSUE TITLE
Example for JsonParser/JsonHandler

### ISSUE THREAD

**Issue by ghost** [ralfstx/minimal-json#106]
Hello developers,

May I ask if you could add examples using `JsonParser`/`JsonHandler` to wiki? It would help a lot. Especially use case of 2 type parameters in `JsonHandler<?, ?>` is not clear in docs.

Thank you,

**Comment by bernardosulzbach** [comment]
Thank you for the suggestion, @hkcorac. I'm quite busy lately but hopefully this will eventually have some examples.

**Comment by thjaeckle** [comment]
Hi. In Eclipse Ditto we have an example of an `JsonHandler` implementation:
https://github.com/eclipse/ditto/blob/master/json/src/main/java/org/eclipse/ditto/json/DittoJsonHandler.java
https://github.com/eclipse/ditto/blob/master/json/src/main/java/org/eclipse/ditto/json/DefaultDittoJsonHandler.java

**Comment by ghost** [comment]
@bernardosulzbach @thjaeckle 

Thank you very much. From reading the Eclipse source code, I was able to understand `JsonHandler`. If I could come up with some example I will send it to you. (But I'm sorry I'm not sure...)
