### ISSUE TITLE
Provide static factory methods for JsonArray

### ISSUE THREAD

**Issue by ralfstx** [ralfstx/minimal-json#12]
Ideally, these factory methods should support varargs. Not sure about the method name.

    JsonArray.createArray( 1, 2, 3 );

Or should the methods go to JsonValue to be next to valueOf( ... )?

    JsonValue.createArray( "a", "b", "c" );

Or on a Util class like so:

    Json.createJsonArray( 1, 2, 3 );

**Comment by sbandara** [comment]
For the sake of keeping minimal-json minimal, a util class `Json` would look the very least attractive to me. Since you already have collection type-specific factories like `JsonArray.readFrom`, my favorite would be `JsonArray.createArray`. Need an assignee?

**Comment by ralfstx** [comment]
@sbandara Actually, I have this idea of a `Json` class for quite some time and find it more and more appealing for the reasons outlined in #52.

> Need an assignee?

Implementation is the least of all efforts, but I'm thankful for thoughts and discussion!
