### ISSUE TITLE
Json Object Merge

### ISSUE THREAD

**Issue by ghost** [ralfstx/minimal-json#23]
Hi,

Thanks for the great library.

Is it possible to support merging for the JsonObject.

json-smart has similar feature: https://code.google.com/p/json-smart/wiki/MergeSample

**Comment by phikal** [comment]
Isn't this closed now?

**Comment by ralfstx** [comment]
Right, thanks! Implemented as of 3f18ecb5c99e82dcfbcd1db3d31f3109ed957820.
