### ISSUE TITLE
Gradle 

### ISSUE THREAD

**Issue by Euphrates-Media** [ralfstx/minimal-json#39]
How can I install minimal-json library using Gradle?

Thank

**Comment by ralfstx** [comment]
Gradle can handle Maven dependencies, see http://www.gradle.org/docs/current/userguide/dependency_management.html#sub:maven_central

The following should work:
```
repositories {
    mavenCentral()
}
dependencies {
    compile 'com.eclipsesource.minimal-json:minimal-json:0.9.2'
}
```
