### ISSUE TITLE
Add to doc code to parse both object and array json string

### ISSUE THREAD

**Issue by julien-diener** [ralfstx/minimal-json#41]
Hi,

I was looking for a way to parse both json object or array and test afterward which one it is. I found a way but I think it should be added to the readme doc. Here is what I did:

        try{
            JsonValue value = JsonValue.readFrom(jsonString);
            if (value instanceof JsonObject) {
                object = (JsonObject) value;
            } else {
                array = (JsonArray) value;
            }
        }catch(RuntimeException e){
            // process error
        }

**Comment by ralfstx** [comment]
You can use the `value.isXxx()` methods for checking the type and `value.asXxx()` for conversion. For example:
```java
if (value.isArray()) {
  array = value.asArray();
} else if (value.isObject()) {
  object = value.asObject();
}
```

Where would you expect this example? Somewhere in the JavaDoc or on the GitHub page? I plan on setting up the GitHub wiki pages to add some more detailed documentation.

**Comment by julien-diener** [comment]
Thanks for the advise.
I am not sure where would be the best place to find this example. I thought about the readme because that is where I looked and did not find it. Now, I just wanted to share this little use case as it could be useful to others.
