### ISSUE TITLE
Use JSONObject and JSONArray class name?

### ISSUE THREAD

**Issue by julien-diener** [ralfstx/minimal-json#42]
Why have you choose to not use the standard class names with upper `JSON`?

You could add `JSONObject` and `JSONArray` as empty subclasses, and have both?

**Comment by ralfstx** [comment]
There's no "standard" class name. For acronyms in Java class names, both spellings are common, all-uppercase and camel-case. For example, the Gson parser also calls it `JsonObject`, others `JSONObject`. Another popular example is `HttpServlet` in javax.servlet.http.

I follow Joshua Bloch's advice in *Effective Java, 2nd edition, pg. 238* to use camel-case for acronyms as well to improve readability. He makes the point that the class name `HttpUrl` is easier to read than `HTTPURL`.

**Comment by julien-diener** [comment]
When saying "standard" I was thinking about the [json api given by json.org](http://www.json.org/java/).
Now, I previously used json-simple, so I tought it was the "only" standard, but if gson use another one, I guess it is just a matter of choice.
(and I agree that camel-case is better for long acronyms)
