### ISSUE TITLE
Hjson

### ISSUE THREAD

**Issue by laktak** [ralfstx/minimal-json#46]
I just wanted to thank you for minimal-json. I used it as a base for a [Hjson](http://hjson.org/) implementation.

https://github.com/laktak/hjson-java

**Comment by ralfstx** [comment]
Cool! Thanks for the note.

Surprised that your parser has only 80 LOC more than the minimal-json one!

**Comment by angelozerr** [comment]
@laktak perhaps you could do a PR to add your project at https://github.com/ralfstx/minimal-json/blob/master/README.md#who-is-using-minimal-json
