### ISSUE TITLE
Provide minimal-json SNAPSHOT with maven with sonatype

### ISSUE THREAD

**Issue by angelozerr** [ralfstx/minimal-json#47]
Like J2V8, it should be cool if SNAPSHOT minimal-json could be available at https://oss.sonatype.org/content/repositories/snapshots/com/eclipsesource/

**Comment by ralfstx** [comment]
Thanks for the suggestion. I was not aware of this possibility. Snapshots are now available at https://oss.sonatype.org/content/repositories/snapshots/com/eclipsesource/minimal-json/.

The process is still manual but simple enough (`mvn clean deploy`). I'll also look into an automated deployment by the CI.

**Comment by ralfstx** [comment]
Use `deploy.sh` in `com.eclipsesource.json` to deploy snapshots.
