### ISSUE TITLE
minimal-json 0.9.3 maven dependency not usable

### ISSUE THREAD

**Issue by thjaeckle** [ralfstx/minimal-json#55]
Hi there.

With version 0.9.3 which is available in maven central:
http://search.maven.org/#artifactdetails|com.eclipsesource.minimal-json|minimal-json|0.9.3|bundle

it seems there was a maven parent pom introduced.
But this parent pom is not available in Maven central, so when using minimal-json 0.9.3 my build fails with:
```
Failed to collect dependencies at com.eclipsesource.minimal-json:minimal-json:jar:0.9.3: Failed to read artifact descriptor for com.eclipsesource.minimal-json:minimal-json:jar:0.9.3: Could not find artifact com.eclipsesource.minimal-json:parent:pom:0.9.3
```

**Comment by angelozerr** [comment]
It's the same issue than https://github.com/ralfstx/minimal-json/issues/48

**Comment by jitpack-io** [comment]
Perhaps this will help in the meantime https://jitpack.io/#ralfstx/minimal-json/0.9.3

**Comment by ralfstx** [comment]
@jitpack-io Thanks, I'll will give it a try!

**Comment by ralfstx** [comment]
Closing as dup of #48
