### ISSUE TITLE
Lighter dependency for mxdump?

### ISSUE THREAD

**Issue by pcarrier** [ralfstx/minimal-json#56]
jackson is a big dependency  (relatively to other components).

`WriterConfig.PRETTY_PRINT` from https://github.com/ralfstx/minimal-json offers similar functionality for a tenth of the size.

**Comment by ralfstx** [comment]
What is mxdump? @pcarrier Did you mean to open this issue in another repository?

Happy if minimal-json suits your needs. Just to let you know there is a dependency issue (#48) with the current version in Maven Central that will be fixed in the next version.

**Comment by pcarrier** [comment]
Oops, indeed wrong window. Sorry.
