### ISSUE TITLE
StackOverflowError when Json.parse()'ing a deeply nested JSON

### ISSUE THREAD

**Issue by thjaeckle** [ralfstx/minimal-json#61]
Hi.
We found out that when parsing a very (very very) deeply nested JSON Object (~ 4.000 levels) with `Json.parse(String)` minimaljson runs out of "Stack" with a `java.lang.StackOverflowError` (which is quite understandable) :)
Of course this is no "use case" for us - it just came up during a pentest which then caused a JVM crash.

Would it be possible to add a configuration to the `JsonParser` which configures a maximum nesting level?
And then throwing a `ParseException` when parsing a too deeply nested JSON-String.

**Comment by ralfstx** [comment]
That's an interesting finding, thanks! I guess the maximum stack size depends on the VM and probably even on the operating system, so it would be hard to guess. But we could explicitly catch `StackOverflowError` and throw a `ParseException`.

**Comment by thjaeckle** [comment]
That's we we now also do as a workaround.
The question is if this should not be handled earlier (fail fast ;))?
MongoDB's BSON parser for example throws a `org.bson.BsonSerializationException: Maximum serialization depth exceeded (does the object being serialized have a circular reference?).` at about 500-1000 nested levels.

It would be quite easy to "count" the level in `JsonParser.readValue()`:
```
case '{':
  currentLevel++;
  return readObject();
```
And the counterpart in `JsonParser.readObject()`:
```
if (readChar('}')) {
  currentLevel--;
  return object;
}
```
And throw the `ParseException` at a specified or configured level.

**Comment by ralfstx** [comment]
I agree. Since `StackOverflowError` is a subclass of `Error`, it

> indicates serious problems that a reasonable application should not try to catch.

It's certainly better to terminate before the VM goes out of resources.

**Comment by mafagafogigante** [comment]
@thjaeckle Can you share some specifications of the JVM that crashed?

I agree with a limit about 1K, if anyone needs more than that with JSON, their data is very badly structured.

**Comment by thjaeckle** [comment]
For reproducing locally it was an Oracle JDK 1.8.0_45 - without `-Xss` explicitly set.
But it occurred at some point also on the production system with an OpenJDK 1.8.0_65 started with `-Xss1M`.
