### ISSUE TITLE
Retrieving line of JsonValue in file?

### ISSUE THREAD

**Issue by jackwilsdon** [ralfstx/minimal-json#62]
Is it possible to find the line of a JsonValue in a file? I'd like to throw an exception relating to an invalid field value and it would be nice if I could provide the line of the issue, also meaning I can retrieve the actual text itself to include in the exception.

It would be useful for generating exceptions like this:

```
Failed to parse JSON!
"myValue" can't be null on line 7:
    ...
    "myValue": null,
    ...
```

**Comment by mafagafogigante** [comment]
I am not the maintainer, but I am almost sure I know the code enough the reply this. No, there is not a way to retrieve the line number.

The JsonParser class throws exceptions with the line number, but those refer to invalid JSON (syntactically), not an invalid value (semantically).

A good alternative may be logging some context together with the invalid value (other values, the object or array the value is in, etc.)

Note that many production JSON files only have a single line, usually where performance matters the most.

Lastly, please understand that this is an awesome thing. If you could get the line from where a value came from it would likely imply that each value stored its line, which could decrease performance substantially. Also, not being able to see the exact JSON file is a **feature**, as it adds abstraction.

Good luck with your endeavors.

**Comment by sbandara** [comment]
Ralf intends to provide a streaming API for minimal-json. Among many things this will allow you to validate values and throw context-rich exceptions just as you described. You could have a look at my pull request to this project from a while ago. You can obtain the line number of the offending value from the `ParserContext` object that is passed along with each parsing event.

**Comment by ralfstx** [comment]
That's right, this should be possible with the streaming API. It's still on my list and hope to include it in the next release. Closing as a dup of #17.
