### ISSUE TITLE
Json.array() should return JsonArray and it returns JsonValue

### ISSUE THREAD

**Issue by clasen** [ralfstx/minimal-json#67]
Json.array() should return JsonArray and it returns JsonValue.
I think that this is an issue.

this example:
```
JsonArray user = Json.array().add("Bob").add(42);
// -> ["Bob", 42]
```
don't work without casting

Thanks,

**Comment by mafagafogigante** [comment]
You are right. Furthermore, other Json#array methods work that way.

**Comment by ralfstx** [comment]
Absolutely!
