### ISSUE TITLE
Using minimal-json without StringWriter

### ISSUE THREAD

**Issue by tsatatwer** [ralfstx/minimal-json#68]
I am new to github and  not sure if I am in correct place here??
I am developing a web project and I am  using TeaVM  an ahead-of-time translating compiler (transpiler) from Java bytecode to JavaScript , and it has some restriction of some parts of JDK can used in TeaVM for example java.lang.reflect not fully supported 
and among not supported classes is java.io.StringWriter witch used by minimal-json so is it possible to get a version of minimal-json can run under this environment .thanks

**Comment by mafagafogigante** [comment]
I don't think a version of minimal-json which does not use StringWriter already exists. I also do not believe anyone is willing to spend their time working for free for such a specific adaptation.

It seems like you will have to do this yourself.

**Comment by tsatatwer** [comment]
Are you the author of  minimal-json ?? and what for is developed then?? 
There are many web projects using GWT and TeaVM  , for my project I have other options witch not include using JSON any way.

**Comment by mafagafogigante** [comment]
> Are you the author of minimal-json ??

No, I am just a user.

> and what for is developed then??

It is developed to be used.

I can barely understand your English. However, I am still going to try to reply.

> There are many web projects using GWT and TeaVM , for my project I have other options witch not include using JSON any way.

Why don't you use one of those options or another JSON library? You are not doing anyone a favor by using an open-source library or not. Instead, you are creating noise on an issue tracker about your specific requirements hoping that someone else will do your job for you. You should be able to fork this library and replace StringWriter by something that works under your environment.

**Comment by tsatatwer** [comment]
>I can barely understand your English. However, I am still going to try to reply.

Oh many thanks for yours nice words!!! English is not my native language I am a German I try my best.

>Why don't you use one of those options or another JSON library? You are not doing anyone a favor >by using an open-source library or not. Instead, you are creating noise on an issue tracker about >your specific requirements hoping that someone else will do your job for you. You should be able to >fork this library and replace StringWriter by something that works under your environment.
Noise?? I just ask a small question?? only one post and look to my first line of text :
>I am new to github and not sure if I am in correct place here??.

It seem to me , for you it is very easy to throw bad words on other peoples , I can do the same but NO I will respect this thread and the author of minimal-json.

**Comment by ralfstx** [comment]
@tsatatwer I'm sorry for not responding yet, I've been too busy these days.

Do you know if `StringWriter` is the only class used in minimal-json that is not supported by GWT and TeaVM? How about `StringReader`, which is used for serialization?

Also, do you know if there is a specific reason for not including this class in these libraries?

**Comment by tsatatwer** [comment]
Many thanks for your response and sorry for the delay from my side too. I have waited your answer several days and I am happy to get it now.
For TeaVM the StringReader class is supported 100% that mean the class with all its methods are supported and this the link : http://teavm.org/jcl-support/0.3.x/packages/java.io.html

>Also, do you know if there is a specific reason for not including this class in these libraries?

I think both have different reasons not to use all jdk classes, but I don't know exactly way they support some classes and other not??? but for TeaVM maybe a time and resource issue??sure I wish if they support all jdk classes at the same time I appreciate there efforts to offer these tools and platform and also developers like you offer library improve software developments.

**Comment by ralfstx** [comment]
> http://teavm.org/jcl-support/0.3.x/packages/java.io.html

Looking at this list, it seems that at least `ObjectInputStream` is also unsupported, so I wonder if this would be an issue. As an experiment, could you try to include the source code of `StringWriter` from the JDK and see if your code works?

One more question: If I understand correctly, you're translating Java code to JavaScript, where there is certainly a JSON parser available. Wouldn't it be an option to use something like GWT's [JSNI](http://www.gwtproject.org/doc/latest/DevGuideCodingBasicsJSNI.html)?

**Comment by tsatatwer** [comment]
Thanks for your suggestion and time I will give it a test and let you know.thanks again

**Comment by tsatatwer** [comment]
>One more question: If I understand correctly, you're translating Java code to JavaScript, where there >is certainly a JSON parser available. Wouldn't it be an option to use something like GWT's JSNI?
YES it is an option with GWT and for my project at server side I am using minimal-json without any restriction . 
So the issue can be closed and I would to thank you for your support and I appreciate your efforts developing such valuable library .
