### ISSUE TITLE
Json parser from XML

### ISSUE THREAD

**Issue by s4kibs4mi** [ralfstx/minimal-json#71]
Requesting a feature to parse JSON from XML data which will create JSON from XML value.

**Comment by neuhaus** [comment]
What feature? It's already there. You can use any XML parser of your choosing to parse the XML, then use minimal-json to generate the JSON.

**Comment by ralfstx** [comment]
I agree with @neuhaus. Sounds like you're requesting a convenience API that can be implemented outside of minimal-json. Please keep in mind that this project aims at providing a *minimal* JSON parser / generator.
