### ISSUE TITLE
Syntax Error in example JSON

### ISSUE THREAD

**Issue by RS1980** [ralfstx/minimal-json#73]
There is a syntax error in the example JSON in the readme in:
https://github.com/ralfstx/minimal-json#example-extract-nested-contents

the line:     "quantity": 10,
has an erroneous comma at the end.

It took me one hour before I realized that actually the example code had an error... :) which broke my hello world example...

**Comment by mafagafogigante** [comment]
Should be merged soon, @RS1980.

Thanks for pointing it out.

**Comment by ralfstx** [comment]
Thanks guys! PR is merged.
