### ISSUE TITLE
JsonObject.getString(String name, String defaultValue)

### ISSUE THREAD

**Issue by ohyesx** [ralfstx/minimal-json#76]
the filed "goback" is Number
but i want to save it use String

String goback = jsonObj.getString("goback", "");

i get error message
ERROR Unexpected error occurred in scheduled task.
java.lang.UnsupportedOperationException: Not a string: 0
at com.eclipsesource.json.JsonValue.asString(JsonValue.java:389)

--------------------------------------------------------
JsonObject
public String getString(String name, String defaultValue) {
　　JsonValue value = get(name);
　　return value != null ? value.asString() : defaultValue;
}
--------------------------------------------------------
Suggest 
       return value != null ? value.**as**String() : defaultValue;
=>  return value != null ? value.**to**String() : defaultValue;

can fix this error
An object that is not null should be converted to a string

**Comment by mafagafogigante** [comment]
> An object that is not null should be converted to a string

No, I don't think so. If you want a String from the JSON file write a string to the JSON file or resolve it on your own application code. Get a value instead of a string, if it is null, resolve how it is best, otherwise, return the result of its toString() method.

The method you are proposing to change is called `getString`, I think most users would not be satisfied if it returned a complex JSON object string representation instead of throwing an exception.

**Comment by ohyesx** [comment]
Hi mafagafogigante, thank you for your reply

My english is poor.
I tried to express my problems by google translate.
In fact, I very much agree with the original design
For programmers, this is correct.

But sometimes we may want to be less strict, because json data sources may be some problems
For example, **the data source define the field "goback" is String**, but when I read the url...
**the url response "goback" : 0  <--- very bad... it is number , not String**

If i follow the real data, i can use the metod
Int goback = jsonObj.getInt("goback", -1);

But I do not want to do that
Because maybe one day the source url fix it , and my code will fail again
I want to make the code robust and simple

So I have to do this to avoid error, regardless of "goback" is number or string
String goback = jsonObj.get("goback").toString();  // but i can't set defaultValue

If i want to set defaultValue
String field1= jsonObj.getString("field1", "");
String field2= jsonObj.getString("field2", "");
String goback = jsonObj.get("goback").toString();
if(goback == null){
    goback = "";   // ok ... i can set defaultValue, but the code a little ugly
}
String field4 = jsonObj.getString("field4", "");
.....

I just believe programmers know what they are doing.
So i wish can use 
String goback = jsonObj.get("goback", defaultValue);

This is just my personal thoughts
For the author design I still quite agree

**Comment by mafagafogigante** [comment]
I understand the issue you are having, but I still think it is not the library which should be able to deal with malformed JSON.
