### ISSUE TITLE
Cannot use Json.array() to create inline arrays

### ISSUE THREAD

**Issue by hcoles** [ralfstx/minimal-json#79]
The example shown in the readme of creating an array does not compile

`JsonArray user = Json.array().add("Bob").add(42);`

The return type of `Json.array()` is `JsonValue` rather than `JsonArray` so the add method is not available without casting.

**Comment by mafagafogigante** [comment]
@hcoles fixed on master [here](https://github.com/ralfstx/minimal-json/blob/master/com.eclipsesource.json/src/main/java/com/eclipsesource/json/Json.java#L153) isn't it?

**Comment by hcoles** [comment]
Ah, so it is.

When is a release expected?
