### ISSUE TITLE
Timeout Period?

### ISSUE THREAD

**Issue by drewlane** [ralfstx/minimal-json#96]
The web service I'm using is very slow and can often takes 30 seconds. The parser seems to be timing out before then. Can I increase the timeout?

**Comment by bernardosulzbach** [comment]
I don't think that this project should even be measuring parsing time. This is a network problem and should be treated as one. Just start a thread for parsing the input stream and time it out if it takes too long.

**Comment by ralfstx** [comment]
Right, the parser does not have any timeout. It must be another component in your system that times out.
