### ISSUE TITLE
ArrayIndexOutOfBoundsException when call getString() on JsonObject

### ISSUE THREAD

**Issue by romweinstein** [ralfstx/minimal-json#97]
Hi,
In case a JsonObject contains more than 127 fields when removing a filed and than get a field sometimes throws IndexOutOfBoundsException

[example.txt](https://github.com/ralfstx/minimal-json/files/1963547/example.txt)

Run the code on example : 
 JsonObject jsonObject = Json.parse(s).asObject();
  jsonObject.remove("x_0");
  jsonObject.getString("x_7",null);

**Comment by ralfstx** [comment]
Good catch, thanks for the but report @romweinstein!
